apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /host/path # CHANGE - plugin path at host
        containerPath: /opt/spire/external-plugin/k8s_psat_tpm_devid # DO NOT CHANGE - path made available for containers
