name: Tests

on:
  pull_request: {}


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
    - uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: latest

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

  integration-swtpm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install socat
      run: sudo apt-get update; sudo apt-get install socat &
    - name: Build binaries
      run: make build

    # Seting up TPM
    - name: Basic environment build up
      run: mkdir ~/k8s-mount; cd dev/provisioning; make build; make setup-provisioning;
    - name: Setup swtpm
      run: cd dev/provisioning; DEFAULT_TPM_SOCKET=~/k8s-mount/swtpm.sock make run-swtpm &
    - name: Start provisioning-server
      run: sleep 15; cd dev/provisioning; make provisioning-server &
    - name: Run provisioning-agent
      run: cd dev/provisioning; DEFAULT_TPM_SOCKET=~/k8s-mount/swtpm.sock make provisioning-agent
    - name: Copy all files to cluster mount directory
      run: cp build/linux/amd64/devid_psat_attestor_* dev/provisioning/swtpm-container/manufacture-tpm/output/ekroot.pem dev/provisioning/conf/server/provisioning-ca.crt dev/provisioning/out/devid-* ~/k8s-mount/; ls ~/k8s-mount
  
    # General configuration
    - name: Calculate agent shasum 
      run: cd build/linux/amd64; agent_sum=$(sha256sum devid_psat_attestor_agent | sed 's/ .*//g')
    - name: Calculate server shasum 
      run: cd build/linux/amd64; server_sum=$(sha256sum devid_psat_attestor_server | sed 's/ .*//g')
    - name: Update agent configuration shasum value 
      run: sed -i "s/plugin_checksum = \".*\"/plugin_checksum = \"$agent_sum\"/g" dev/common/agent-configmap.yaml
    - name: Update server configuration shasum value 
      run: sed -i "s/plugin_checksum = \".*\"/plugin_checksum = \"$server_sum\"/g" dev/common/server-configmap.yaml

      # Spinning up cluster and deploying
    - name: Download and install kind
      run: curl -Lo ./kind  "https://kind.sigs.k8s.io/dl/v0.14.0/kind-$(uname)-amd64"; chmod +x ./kind
    - name: Download and install kubectl
      run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"; sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - name: Apply necessary configuration to kind-conf file
      run: cd ~; HOST_PATH=$(pwd); cd -; sed -i "s:/host/path:$HOST_PATH/k8s-mount:g" dev/kind/kind-conf.yaml
    - name: Start kind cluster
      run: ./kind create cluster --config dev/kind/kind-conf.yaml
    - name: Deploy SPIRE
      run: cd dev/kind; chmod +x deploy-spire.sh; ./deploy-spire.sh; sleep 20
    - name: Waiting on the agent to become ready
      run: kubectl wait pod --for=condition=ready -n spire -l app=spire-agent  
